blank_issues_enabled: false
contact_links:
  - name: x/vulndb bugs or feature requests
    about: Please use the Go issue tracker for issues related to the x/vulndb project.
    url: https://github.com/golang/go/issues/new?assignees=&labels=vulncheck+or+vulndb&projects=&template=04-vuln.yml&title=x%2Fvuln%3A+issue+title
  - name: Report a security vulnerability in the Go project
    about: See here for our security policy.
    url: https://go.dev/security
